apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: argocd 
  labels:
    app: loki
    group: grafana
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app: loki
    group: grafana

---

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: loki
  namespace: argocd 
  labels:
    app: loki
    group: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
      group: grafana
  template:
    metadata:
      labels:
        app: loki
        group: grafana

    spec:
      containers:
        - name: loki
          image: grafana/loki:2.9.2 
          imagePullPolicy: Always
          args: ['-config.file=/etc/loki/loki-config.yaml'] 
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki/
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
