apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
    group: grafana
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: grafana
    group: grafana

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: grafana
  namespace: argocd
  labels:
    app: grafana
    group: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      group: grafana
  template:
    metadata:
      labels:
        app: grafana
        group: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.0.0
          imagePullPolicy: Always
          env:
            - name: GF_EXPLORE_ENABLED
              value: "true"
