# Set global options
data_dir: "/var/lib/vector"

# Vector's API (disabled by default)
# Enable and try it out with the `vector top` command
# NOTE: this is _enabled_ for helm chart deployments, see: https://github.com/vectordotdev/helm-charts/blob/develop/charts/vector/examples/datadog-values.yaml#L78-L81
api:
  enabled: false
# address = "127.0.0.1:8686"

# Ingest data by tailing one or more files
sources:
  my_app_logs:
    type: "file"
    include:
      - "/var/log/*.log" # supports globbing
    ignore_older_secs: 86400     # 1 day

# Send structured data to a short-term storage
sinks:
  loki_klaster:
    inputs:
      - "my_app_logs"       # only take sampled data
    type: "loki"
    endpoints:
      - "hhtp://loki-stack:3100"
