apiVersion: v1
kind: Service
metadata:
  name: time-app-service
  namespace: argocd # Теперь в неймспейсе argocd
spec:
  type: NodePort
  selector:
    app: time-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31000 # Выбранный вами NodePort