apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector
  namespace: monitoring # Убедитесь, что неймспейс совпадает
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vector
rules:
  - apiGroups: [""]
    resources:
      - "nodes"
      - "nodes/proxy"
      - "pods"
      - "namespaces"
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources:
      - "replicasets"
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources:
      - "events"
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vector
subjects:
  - kind: ServiceAccount
    name: vector
    namespace: monitoring
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: vector
  namespace: monitoring # Убедитесь, что неймспейс совпадает
  labels:
    app: vector
spec:
  selector:
    matchLabels:
      app: vector
  template:
    metadata:
      labels:
        app: vector
    spec:
      serviceAccountName: vector
      terminationGracePeriodSeconds: 5
      containers:
        - name: vector
          image: timberio/vector:0.36.0-alpine # Используйте конкретную версию
          imagePullPolicy: IfNotPresent
          env:
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: var-log
              mountPath: /var/log
            - name: var-lib-docker
              mountPath: /var/lib/docker
              readOnly: true
            - name: var-lib-kubelet
              mountPath: /var/lib/kubelet
              readOnly: true
            - name: vector-config
              mountPath: /etc/vector/vector.yaml
              subPath: vector.yaml
              readOnly: true
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 50m
              memory: 100Mi
      volumes:
        - name: var-log
          hostPath:
            path: /var/log
        - name: var-lib-docker
          hostPath:
            path: /var/lib/docker
        - name: var-lib-kubelet
          hostPath:
            path: /var/lib/kubelet
        - name: vector-config
          configMap:
            name: vector-config