apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-config
  namespace: monitoring
data:
  vector.yaml: |
    # Источник логов: сбор логов из Kubernetes
    sources:
      kubernetes_logs:
        type: kubernetes_logs
        # ИСПРАВЛЕНИЕ 1: Добавляем self_node_name
        self_node_name: "{{ HOSTNAME }}"

    # Преобразование логов (парсинг JSON, добавление лейблов)
    transforms:
      # Для логов Argo CD, которые уже в JSON формате
      argo_cd_json_parser:
        type: remap
        inputs:
          - kubernetes_logs
        source: |
          if .kubernetes.namespace_name == "argocd" {
            # ИСПРАВЛЕНИЕ 2: Явно приводим .message к строке перед проверками
            # Используем `to_string` для большей безопасности, чтобы избежать падения,
            # если .message не является строкой.
            msg_str = to_string(.message) ?? ""
            if msg_str != null && starts_with(msg_str, "{") && ends_with(msg_str, "}") {
              parsed = parse_json(msg_str) ?? null
              if parsed != null {
                . = merge!(., parsed)
                del(.message)
              }
            }
            .kubernetes.container_name = .kubernetes.pod_labels."app.kubernetes.io/component" || .kubernetes.container_name
            .kubernetes.app_name = .kubernetes.pod_labels."app.kubernetes.io/name"
            .kubernetes.instance = .kubernetes.pod_labels."app.kubernetes.io/instance"

            .loki.kubernetes_namespace = .kubernetes.namespace_name
            .loki.kubernetes_pod = .kubernetes.pod_name
            .loki.kubernetes_container = .kubernetes.container_name
            .loki.level = .level || "info"
          } else {
            abort
          }

    # Назначение: отправка логов в Loki
    sinks:
      loki_sink:
        type: loki
        inputs:
          - argo_cd_json_parser
        endpoint: http://loki-stack-loki.monitoring.svc.cluster.local:3100/api/prom/push
        encoding:
          codec: json
        labels:
          job: kubernetes-pods
          host: "{{ HOSTNAME }}"
          namespace: "{{ kubernetes.namespace_name }}"
          pod: "{{ kubernetes.pod_name }}"
          container: "{{ kubernetes.container_name }}"
          app_name: "{{ kubernetes.app_name }}"
          instance: "{{ kubernetes.instance }}"
          component: "{{ kubernetes.container_name }}"
        remove_label_fields: true