apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: prod

  source:
    repoURL: 'git@github.com:Anvarking/CD_Project.git'
    targetRevision: HEAD
    path: postgresql
    helm:
      valueFiles:
        - values-postgresql.yaml

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true      
      selfHeal: true    
    syncOptions:
    - CreateNamespace=true