apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: git@github.com:Anvarking/CD_Project.git
    targetRevision: HEAD
    path: rabbitmq
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true