apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-dev
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: git@github.com:Anvarking/CD_Project.git
    targetRevision: HEAD
    path: redis
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true